version: '3'
services:
  web:
    build: './web'
    networks:
      - app-network
    ports:
      # - "3000:3000"
      - "3000"

  search:
    build: './search'
    networks:
      - app-network
    ports:
      # - "3001:3000"
      - "3000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices

  books:
    build: './books'
    networks:
      - app-network
    ports:
      # - "3002:3000"
      - "3000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices

  videos:
    build: './videos'
    networks:
      - app-network
    ports:
      # - "3003:3000"
      - "3000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices

  db:
    image: mongo
    networks:
      - app-network
    ports:
      # - "27017:27017"
      - "27017"
    volumes:
      - dbdata:/data/db

  nginx:
    image: nginx:latest
    networks:
      - app-network
    ports:
      - "8080:8080"
    volumes:
      - ./web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - books
      - search
      - videos

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: